# Generated by Django 4.1.2 on 2022-11-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_progress_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plan'),
        ),
    ]
