# Generated by Django 4.1.2 on 2022-11-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_complete_progress_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['estimate_date']},
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='status',
            new_name='is_complete',
        ),
    ]
