# Generated by Django 4.1.2 on 2022-11-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_plan_options_alter_progress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
