# Generated by Django 4.1.2 on 2022-11-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_plan_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
