# Generated by Django 4.1.2 on 2022-12-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_plan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('Study', 'Study'), ('Work', 'Work'), ('Life', 'Life')], default='Study', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(),
        ),
    ]
